/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pasta_menu;

import Pasta_Login.cadastrar_Login_VIEW;
import Pasta_cliente.cliente_Cadastrar_VIEW;
import Pasta_estoque.Estoque_consulta_VIEW;
import Pasta_pagamento.view_pagamento;
import Pasta_pedidos.CadastroPedidosView;

/**
 *
 * @author vsant
 */
public class menu_VIEW extends javax.swing.JFrame {

    /**
     * Creates new form menu_VIEW
     */
    public menu_VIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_cadastrar_usuario = new javax.swing.JButton();
        btn_cliente = new javax.swing.JButton();
        btn_cardapio = new javax.swing.JButton();
        btn_pedidos = new javax.swing.JButton();
        btn_pagamento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, 30));

        btn_cadastrar_usuario.setBackground(new java.awt.Color(233, 180, 101));
        btn_cadastrar_usuario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_cadastrar_usuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrar_usuario.setText("USUÁRIO");
        btn_cadastrar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 150, -1));

        btn_cliente.setBackground(new java.awt.Color(233, 180, 101));
        btn_cliente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_cliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_cliente.setText("CLIENTE");
        btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 150, -1));

        btn_cardapio.setBackground(new java.awt.Color(233, 180, 101));
        btn_cardapio.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_cardapio.setForeground(new java.awt.Color(255, 255, 255));
        btn_cardapio.setText("CARDÁPIO");
        btn_cardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cardapioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cardapio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, -1));

        btn_pedidos.setBackground(new java.awt.Color(233, 180, 101));
        btn_pedidos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_pedidos.setForeground(new java.awt.Color(255, 255, 255));
        btn_pedidos.setText("PEDIDOS");
        btn_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedidosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 150, -1));

        btn_pagamento.setBackground(new java.awt.Color(233, 180, 101));
        btn_pagamento.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btn_pagamento.setForeground(new java.awt.Color(255, 255, 255));
        btn_pagamento.setText("PAGAMENTO");
        btn_pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, -1));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_usuarioActionPerformed
       //Esta chamando a tela cadastrar usuario
       cadastrar_Login_VIEW objCadastrarLogin = new cadastrar_Login_VIEW();
       objCadastrarLogin.setLocationRelativeTo(null);
       objCadastrarLogin.setVisible(true);
       
    }//GEN-LAST:event_btn_cadastrar_usuarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clienteActionPerformed
       cliente_Cadastrar_VIEW telacliente_Cadastrar= new cliente_Cadastrar_VIEW();
       telacliente_Cadastrar.setLocationRelativeTo(null);
       telacliente_Cadastrar.setVisible(true);
    
    }//GEN-LAST:event_btn_clienteActionPerformed

    private void btn_cardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cardapioActionPerformed
       Estoque_consulta_VIEW telaEstoque_consulta = new Estoque_consulta_VIEW();
       telaEstoque_consulta.setLocationRelativeTo(null);
       telaEstoque_consulta.setVisible(true);
    
    }//GEN-LAST:event_btn_cardapioActionPerformed

    private void btn_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedidosActionPerformed
         CadastroPedidosView telaCadastroPedidos = new CadastroPedidosView();
         telaCadastroPedidos.setLocationRelativeTo(null);
         telaCadastroPedidos.setVisible(true);
   
    }//GEN-LAST:event_btn_pedidosActionPerformed

    private void btn_pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagamentoActionPerformed
         view_pagamento telaview_pagamento= new view_pagamento();
         telaview_pagamento.setLocationRelativeTo(null);
         telaview_pagamento.setVisible(true);
    
    }//GEN-LAST:event_btn_pagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_VIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar_usuario;
    private javax.swing.JButton btn_cardapio;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_pagamento;
    private javax.swing.JButton btn_pedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
