package Pasta_pagamento;

import java.time.LocalDate;

public class view_pagamento extends javax.swing.JFrame {

    int idPedido = 1;
    double valorPedido = 200.50;

    /**
     * Creates new form view_pagamento
     */
    public view_pagamento() {
        initComponents();
    }
    
    public void importar_Dados(pagamento_DTO objDTO){
        lblIDPedido.setText(Integer.toString(objDTO.getIdPedido()));
        txtVlrPedido.setText(Double.toString(objDTO.getValorPedido()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        mtdPag_comboBox = new javax.swing.JComboBox<>();
        txtVlrPedido = new javax.swing.JTextField();
        lblDinheiro = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        txtDinheiro = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        lblIDPedido = new javax.swing.JLabel();
        btnConsultarPgm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pedido"
            }
        ));
        jScrollPane1.setViewportView(tblPedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 375, 320));

        mtdPag_comboBox.setBackground(new java.awt.Color(233, 180, 101));
        mtdPag_comboBox.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mtdPag_comboBox.setForeground(new java.awt.Color(255, 255, 255));
        mtdPag_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEBITO", "CREDITO", "PIX", "DINHEIRO" }));
        mtdPag_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtdPag_comboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(mtdPag_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 160, -1));

        txtVlrPedido.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVlrPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtVlrPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 160, -1));

        lblDinheiro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblDinheiro.setForeground(new java.awt.Color(255, 255, 255));
        lblDinheiro.setText("TOTAL");
        getContentPane().add(lblDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        lblTroco.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTroco.setForeground(new java.awt.Color(255, 255, 255));
        lblTroco.setText("TROCO");
        getContentPane().add(lblTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        txtTroco.setForeground(new java.awt.Color(255, 255, 255));
        txtTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrocoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 160, -1));

        btnFinalizar.setBackground(new java.awt.Color(233, 180, 101));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("FINALIZAR");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 160, -1));

        txtDinheiro.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 160, -1));

        btnCalcular.setBackground(new java.awt.Color(233, 180, 101));
        btnCalcular.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 160, -1));

        lbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 255, 255));
        lbl.setText("IDPedido");
        getContentPane().add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        lblIDPedido.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblIDPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblIDPedido.setText("ID");
        getContentPane().add(lblIDPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        btnConsultarPgm.setBackground(new java.awt.Color(233, 180, 101));
        btnConsultarPgm.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultarPgm.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarPgm.setText("CONSULTAR PAG.");
        btnConsultarPgm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPgmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarPgm, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 160, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAGAMENTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, -1));

        jPanel1.setBackground(new java.awt.Color(120, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mtdPag_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtdPag_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mtdPag_comboBoxActionPerformed

    private void txtVlrPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVlrPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVlrPedidoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        String mtdPagamento = "";
        LocalDate data = LocalDate.now();
        double vlrPedido = 0;
        int IDPedido = idPedido;

        mtdPagamento = (String) mtdPag_comboBox.getSelectedItem();
        vlrPedido = Double.parseDouble(txtVlrPedido.getText());
        IDPedido = Integer.parseInt(lblIDPedido.getText());
        
        pagamento_DTO dto = new pagamento_DTO();
        dto.setData(data);
        dto.setFormaDePagamento(mtdPagamento);
        dto.setIdPedido(IDPedido);
        dto.setValorPedido(vlrPedido);

        pagamentoDAO dao = new pagamentoDAO();
        dao.save(dto);

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void txtTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrocoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double vlrPedido = 0, vlrDinheiro = 0, vlrTotal = 0, vlrTroco = 0;
        vlrPedido = Double.parseDouble(txtVlrPedido.getText());
        vlrDinheiro = Double.parseDouble(txtDinheiro.getText());
        vlrTroco = vlrDinheiro - vlrPedido;
        txtTroco.setText(String.valueOf(vlrTroco));
    

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnConsultarPgmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPgmActionPerformed
        consultarPagamento telaConsultaPagamento = new consultarPagamento();
        telaConsultaPagamento.setLocationRelativeTo(null);
        telaConsultaPagamento.setVisible(true);
    }//GEN-LAST:event_btnConsultarPgmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_pagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnConsultarPgm;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblDinheiro;
    private javax.swing.JLabel lblIDPedido;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JComboBox<String> mtdPag_comboBox;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtVlrPedido;
    // End of variables declaration//GEN-END:variables
}
