/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pasta_pedidos;

import Pasta_Login.usuario_DTO;
import Pasta_cliente.cliente_DTO;
import Pasta_estoque.Estoque_DAO;
import Pasta_estoque.estoque_DTO;
import Pasta_pagamento.pagamento_DTO;
import Pasta_pagamento.view_pagamento;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jeff & Carla
 */
public class CadastroPedidosView extends javax.swing.JFrame {
    
    int Ultimo_ID_Gerado_no_Pedido;
    double valor_Total_do_Pedido;
    double getPreco;
    
    
    estoque_DTO objDTO = new estoque_DTO();
    Estoque_DAO objDAO = new Estoque_DAO();
    pedidos_DAO objpedidosDAO = new pedidos_DAO();

    /**
     * Creates new form CadastroPedidosView
     */
    public CadastroPedidosView() {
        initComponents();
        txt_vlr_total.setText(String.valueOf(0));
        txt_ID_Cliente.setText(String.valueOf(0));
        txtValor.setVisible(false);
    }
    
    
    public void exportarDados_Cliente(cliente_DTO objDTO){
            txt_ID_Cliente.setText(Integer.toString(objDTO.getChave_Primaria()));
            txt_Nome_Cliente.setText(objDTO.getNome());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        txtAreaDescricao = new java.awt.TextArea();
        AreaObservacao = new java.awt.TextArea();
        btnSalvar = new java.awt.Button();
        btnPagamento = new java.awt.Button();
        btnAdicionar = new java.awt.Button();
        btnPesquisar = new java.awt.Button();
        btnLimpar = new java.awt.Button();
        btn_consultar = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        Quantidade = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JLabel();
        txtObservacao = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txt_ID_Cliente = new javax.swing.JTextField();
        txt_Nome_Cliente = new javax.swing.JTextField();
        txt_vlr_total = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaPedidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Lanches", "Valor"
            }
        ));
        tabelaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescricaoAutomatica(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 300, 550));

        txtAreaDescricao.setEditable(false);
        txtAreaDescricao.setEnabled(false);
        txtAreaDescricao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtAreaDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 480, 200));

        AreaObservacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(AreaObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 490, 240));

        btnSalvar.setBackground(new java.awt.Color(233, 180, 101));
        btnSalvar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setLabel("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, 80, 40));

        btnPagamento.setBackground(new java.awt.Color(233, 180, 101));
        btnPagamento.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPagamento.setForeground(new java.awt.Color(255, 255, 255));
        btnPagamento.setLabel("PAGAMENTO");
        btnPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 610, 120, 40));

        btnAdicionar.setBackground(new java.awt.Color(233, 180, 101));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setLabel("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 120, 40));

        btnPesquisar.setBackground(new java.awt.Color(233, 180, 101));
        btnPesquisar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setLabel("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 90, 40));

        btnLimpar.setBackground(new java.awt.Color(233, 180, 101));
        btnLimpar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setLabel("LIMPAR");
        btnLimpar.setName("PEDIDOS"); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, 90, 40));

        btn_consultar.setBackground(new java.awt.Color(233, 180, 101));
        btn_consultar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar.setLabel("CONSULTAR");
        btn_consultar.setName("PEDIDOS"); // NOI18N
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, 100, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEDIDOS");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1280, -1));

        Quantidade.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Quantidade.setForeground(new java.awt.Color(255, 255, 255));
        Quantidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quantidade.setText("QUANTIDADE");
        getContentPane().add(Quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 60, 120, -1));

        txtDescricao.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(255, 255, 255));
        txtDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescricao.setText("DESCRIÇÃO");
        getContentPane().add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 480, -1));

        txtObservacao.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtObservacao.setForeground(new java.awt.Color(255, 255, 255));
        txtObservacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtObservacao.setText("OBSERVAÇÃO");
        getContentPane().add(txtObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 490, 20));

        Valor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Valor.setForeground(new java.awt.Color(255, 255, 255));
        Valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Valor.setText("VALOR TOTAL");
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 530, 130, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOME:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        txtValor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtValor.setText(" ");
        txtValor.setEnabled(false);
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 120, 40));

        txtQuantidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 90, 120, 40));

        txt_ID_Cliente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txt_ID_Cliente.setEnabled(false);
        getContentPane().add(txt_ID_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 60, -1));

        txt_Nome_Cliente.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txt_Nome_Cliente.setEnabled(false);
        getContentPane().add(txt_Nome_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, -1));

        txt_vlr_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vlr_totalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_vlr_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 570, 120, 30));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO código da pesquisa para o banco esta aqui nesse botão de Pesquisar
        String filtro="";
        DefaultTableModel pedidos = (DefaultTableModel) tabelaPedidos.getModel();
        pedidos.setNumRows(0);
        ArrayList<estoque_DTO> listaDTO = objDAO.Consultaproduto(filtro);
        
        for (int num = 0; num < listaDTO.size(); num++) {
            pedidos.addRow(new Object[]{
            
                listaDTO.get(num).getId(),
                listaDTO.get(num).getNome(),
                listaDTO.get(num).getPreco(),
                
            });
        }
        
        
        
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        double vlr_produto, resultado=0, qtd_produtos, total,vlr_a_somar,vlr_total_somado,decimal_limitado;
       
       vlr_produto= getPreco;
       qtd_produtos = Double.parseDouble(txtQuantidade.getText());
       
       
       resultado =  (vlr_produto * qtd_produtos);
       
       txtValor.setText(String.valueOf(resultado));
       
       vlr_a_somar= Double.parseDouble(txtValor.getText());
       
       total = Double.parseDouble(txt_vlr_total.getText());
       
       vlr_total_somado = vlr_a_somar + total;
       
       
       txt_vlr_total.setText(String.valueOf(vlr_total_somado));
       txtValor.setText("");
    }//GEN-LAST:event_btnAdicionarActionPerformed
    
    
    
    
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
    txtAreaDescricao.setText("");
    AreaObservacao.setText("");
    
    // Limpa o campo de quantidade
    txtQuantidade.setText("");
    
    // Limpa o campo de valor
    txtValor.setText("");
    txt_vlr_total.setText(String.valueOf(0));

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void DescricaoAutomatica(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescricaoAutomatica
        // TODO add your handling code here:
        Estoque_DAO objDAO = new Estoque_DAO();
        estoque_DTO objDTO = new estoque_DTO();
        
        String
                pegar_id_tabela, pegar_preco_tabela;
        
        int
                linha_clicada_tabela;
        
        linha_clicada_tabela = tabelaPedidos.getSelectedRow();
        pegar_id_tabela = (tabelaPedidos.getModel().getValueAt(linha_clicada_tabela, 0).toString());
        
        objDTO = objDAO.ConsultarID(Integer.parseInt(pegar_id_tabela));
        
        txtAreaDescricao.setText(objDTO.getDescricao());
        
        pegar_preco_tabela = (tabelaPedidos.getModel().getValueAt(linha_clicada_tabela, 2).toString());
        getPreco = Double.parseDouble(pegar_preco_tabela);       
    }//GEN-LAST:event_DescricaoAutomatica

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtValorActionPerformed

    private void btnPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentoActionPerformed
        
        int
                campoIDCliente;
        String
                campoObservacao;
        pedidos_DTO objDTO = new pedidos_DTO();
        
        LocalDate data = LocalDate.now();
        campoObservacao = AreaObservacao.getText();
        campoIDCliente = Integer.parseInt(txt_ID_Cliente.getText());
        
        objDTO.setData(data);
        objDTO.setCampoObservacao(campoObservacao);
        
        if(campoIDCliente != 0){
            
            objDTO.setCampoIDCliente(campoIDCliente);
            
        }
        else if(campoIDCliente == 0) {
            
            campoIDCliente = 1;
            objDTO.setCampoIDCliente(campoIDCliente);
        }
        
        
         Ultimo_ID_Gerado_no_Pedido = objpedidosDAO.Salvar(objDTO);
         valor_Total_do_Pedido = Double.parseDouble(txt_vlr_total.getText());
        
        exportar_Dados();
        
    }//GEN-LAST:event_btnPagamentoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void txt_vlr_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vlr_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vlr_totalActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        Consultar_pedidos telaConsultar_pedidos = new Consultar_pedidos();
        telaConsultar_pedidos.setLocationRelativeTo(null);
        telaConsultar_pedidos.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPedidosView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea AreaObservacao;
    private javax.swing.JLabel Quantidade;
    private javax.swing.JLabel Valor;
    private java.awt.Button btnAdicionar;
    private java.awt.Button btnLimpar;
    private java.awt.Button btnPagamento;
    private java.awt.Button btnPesquisar;
    private java.awt.Button btnSalvar;
    private java.awt.Button btn_consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPedidos;
    private java.awt.TextArea txtAreaDescricao;
    private javax.swing.JLabel txtDescricao;
    private javax.swing.JLabel txtObservacao;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txt_ID_Cliente;
    private javax.swing.JTextField txt_Nome_Cliente;
    private javax.swing.JTextField txt_vlr_total;
    // End of variables declaration//GEN-END:variables


    public void exportar_Dados(){
        pagamento_DTO objDTO = new pagamento_DTO();
        view_pagamento objviewpagamento = new view_pagamento();

        objDTO.setIdPedido(Ultimo_ID_Gerado_no_Pedido);
        objDTO.setValorPedido(valor_Total_do_Pedido);
        
        objviewpagamento.importar_Dados(objDTO);
        
        
        objviewpagamento.setLocationRelativeTo(null);
        objviewpagamento.setVisible(true);
    
    }



}
